name: Run unit tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code - download code from repository
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test